### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by jonoirwinrsa** [SovTech/hacktoberfest-leaderboard#14]
Get the version number from the package.json and show it on the site somewhere

**Comment by dsappet** [comment]
I got it

**Comment by FlopiVG** [comment]
Hi i will take this

**Comment by dsappet** [comment]
> Hi i will take this

I'm already on it.

**Comment by faisal-zulfiqar** [comment]
@jonoirwinrsa I just made the PR #17. Please check it out :)

**Comment by dsappet** [comment]
Not respecting the system here guys.

**Comment by jonoirwinrsa** [comment]
One of these will do

**Comment by FlopiVG** [comment]
Ooops srry guys :(
